{
    'name': 'Soporte Sindicato UPADEP (Argentina)',
    'version': '14.0.3.0.0',
    'description': 'Datos y adecuaciones para soportar el sindicato UPADEP en la localizacion Argentina de Payroll.',
    'summary': 'Agrega conceptos, categorias y precios para el sindicato UPADEP.',
    'author': 'Fabian Cerchi, Exemax',
    'website': '',
    'license': 'LGPL-3',
    'category': 'Payroll',
    'depends': [
        'payroll',
        'l10n_ar_payroll',
        'l10n_ar_hr_contract_labor_union',
        'l10n_ar_payroll_ledger',
        'payroll_contract_advantages',
        'hr_contract',
        'hr_overtime',
    ],
    'data': [
        'data/res_partner.xml',
        'data/lu_upadep_contribution_register.xml',
        'data/lu_upadep_categories_prices.xml',
        'data/lu_upadep_salary_rules.xml',
        'data/lu_upadep_salary_sac_rules.xml',
        'data/hr_overtime_liqfinal.xml',
        'data/lu_upadep_salary_liqfinal_rules.xml',
        'data/lu_upadep_salary_structures.xml',
        'data/lu_upadep_salary_parameter.xml',
        'data/lu_upadep_advantages.xml',
        'data/hr_overtime_types.xml',
        'views/hr_contract.xml',
        'views/hr_payslip.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
